name: Test self-hosted Mac runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macOS, X64]

    steps:
      - name: Machine info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner arch: $RUNNER_ARCH"
          sw_vers
          uname -m
          whoami
